/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import customer.Customer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Noko
 */
public class Edit_frame extends javax.swing.JFrame {

    /**
     * Creates new form Edit_frame
     */
    public Edit_frame() {
        initComponents();
        try {
            data_TextPane.setText(Customer.allCustomers());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showConfirmDialog(null, "Error in database conection!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        data_ScrollPane2 = new javax.swing.JScrollPane();
        data_TextPane = new javax.swing.JTextPane();
        heder_Label = new javax.swing.JLabel();
        comand_jPanel = new javax.swing.JPanel();
        id_Label = new javax.swing.JLabel();
        id_Spinner = new javax.swing.JSpinner();
        first_name_Label = new javax.swing.JLabel();
        first_name_TextField = new javax.swing.JTextField();
        last_name_Label = new javax.swing.JLabel();
        last_name_TextField = new javax.swing.JTextField();
        new_address_Label = new javax.swing.JLabel();
        addres_TextField = new javax.swing.JTextField();
        phone_Label = new javax.swing.JLabel();
        phone_TextField = new javax.swing.JTextField();
        save_Button = new javax.swing.JButton();
        return_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        data_ScrollPane2.setBackground(new java.awt.Color(51, 153, 255));
        data_ScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        data_TextPane.setEditable(false);
        data_TextPane.setBackground(new java.awt.Color(51, 153, 255));
        data_TextPane.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        data_TextPane.setForeground(new java.awt.Color(255, 255, 255));
        data_ScrollPane2.setViewportView(data_TextPane);

        heder_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        heder_Label.setForeground(new java.awt.Color(255, 255, 255));
        heder_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heder_Label.setText("All customers in database");
        heder_Label.setToolTipText("");
        heder_Label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        comand_jPanel.setBackground(new java.awt.Color(51, 153, 255));
        comand_jPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        id_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        id_Label.setForeground(new java.awt.Color(255, 255, 255));
        id_Label.setText("Enter the customer id for changing data");

        first_name_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        first_name_Label.setForeground(new java.awt.Color(255, 255, 255));
        first_name_Label.setText("Enter a new first name:");

        last_name_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        last_name_Label.setForeground(new java.awt.Color(255, 255, 255));
        last_name_Label.setText("Enter a new last name:");

        new_address_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        new_address_Label.setForeground(new java.awt.Color(255, 255, 255));
        new_address_Label.setText("Enter a new address:");

        phone_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        phone_Label.setForeground(new java.awt.Color(255, 255, 255));
        phone_Label.setText("Enter the new phone number:");

        save_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/save.jpg"))); // NOI18N
        save_Button.setToolTipText("SAVE CHANGES");
        save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_ButtonActionPerformed(evt);
            }
        });

        return_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/return.png"))); // NOI18N
        return_Button.setToolTipText("RETURN");
        return_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout comand_jPanelLayout = new javax.swing.GroupLayout(comand_jPanel);
        comand_jPanel.setLayout(comand_jPanelLayout);
        comand_jPanelLayout.setHorizontalGroup(
            comand_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comand_jPanelLayout.createSequentialGroup()
                .addGroup(comand_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comand_jPanelLayout.createSequentialGroup()
                        .addGroup(comand_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(comand_jPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(comand_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(first_name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(first_name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, comand_jPanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(comand_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(last_name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(comand_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(last_name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(comand_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(new_address_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(comand_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(addres_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(comand_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(phone_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(comand_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(phone_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(comand_jPanelLayout.createSequentialGroup()
                                                            .addComponent(save_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(return_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))))))))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comand_jPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(comand_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        comand_jPanelLayout.setVerticalGroup(
            comand_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comand_jPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(id_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(id_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(first_name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(first_name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(last_name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(last_name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(new_address_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addres_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phone_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(comand_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(return_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(data_ScrollPane2)
                    .addComponent(heder_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(comand_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(heder_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data_ScrollPane2))
                    .addComponent(comand_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void return_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_ButtonActionPerformed
        Edit_frame.super.setVisible(false);
        OptionFrame op = new OptionFrame();
        op.setLocationRelativeTo(null);
        op.setVisible(true);
    }//GEN-LAST:event_return_ButtonActionPerformed

    private void save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_ButtonActionPerformed
        int id=Integer.valueOf(id_Spinner.getValue().toString()) ;
        String new_frname = first_name_TextField.getText();
        String new_lastname = last_name_TextField.getText();
        String new_address= addres_TextField.getText();
        String new_phone= phone_TextField.getText();
        if(new_frname.equals("")||new_lastname.equals("")||new_address.equals("")||new_phone.equals("")){
            JOptionPane.showMessageDialog(null, "You have not entered all fields", "Enter all fields",JOptionPane.ERROR_MESSAGE );
        }
        else{
            try {
                Customer.edit_customer_byID(id, new_frname, new_lastname, new_address, new_phone);
                 data_TextPane.setText(Customer.allCustomers());
                 first_name_TextField.setText("");
                 last_name_TextField.setText("");
                 addres_TextField.setText("");
                 phone_TextField.setText("");
                 JOptionPane.showMessageDialog(null, "You have successfully updated your data!", "Update completed", JOptionPane.INFORMATION_MESSAGE);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showConfirmDialog(null, "Error in database conection!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_save_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_frame().setVisible(true);
               
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addres_TextField;
    private javax.swing.JPanel comand_jPanel;
    private javax.swing.JScrollPane data_ScrollPane2;
    private javax.swing.JTextPane data_TextPane;
    private javax.swing.JLabel first_name_Label;
    private javax.swing.JTextField first_name_TextField;
    private javax.swing.JLabel heder_Label;
    private javax.swing.JLabel id_Label;
    private javax.swing.JSpinner id_Spinner;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel last_name_Label;
    private javax.swing.JTextField last_name_TextField;
    private javax.swing.JLabel new_address_Label;
    private javax.swing.JLabel phone_Label;
    private javax.swing.JTextField phone_TextField;
    private javax.swing.JButton return_Button;
    private javax.swing.JButton save_Button;
    // End of variables declaration//GEN-END:variables
}
