/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import customer.Customer;
import javax.swing.JOptionPane;


/**
 *
 * @author Noko
 */
public class New_frame extends javax.swing.JFrame {

    /**
     * Creates new form New_frame
     */
    public New_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        struct_Panel = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        firstname_Label = new javax.swing.JLabel();
        firstname_TextField = new javax.swing.JTextField();
        lastname_Label = new javax.swing.JLabel();
        lastname_TextField = new javax.swing.JTextField();
        address_Label = new javax.swing.JLabel();
        address_TextField = new javax.swing.JTextField();
        phone_Label = new javax.swing.JLabel();
        phone_TextField = new javax.swing.JTextField();
        clear_Button = new javax.swing.JButton();
        heder_Label1 = new javax.swing.JLabel();
        comandPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        returnButton2 = new javax.swing.JButton();
        imgPanel = new javax.swing.JPanel();
        img_for_new = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New customer");

        struct_Panel.setBackground(new java.awt.Color(51, 153, 255));

        dataPanel.setBackground(new java.awt.Color(51, 153, 255));
        dataPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        firstname_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        firstname_Label.setForeground(new java.awt.Color(255, 255, 255));
        firstname_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        firstname_Label.setText("First name:");

        lastname_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lastname_Label.setForeground(new java.awt.Color(255, 255, 255));
        lastname_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lastname_Label.setText("Last name:");

        address_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        address_Label.setForeground(new java.awt.Color(255, 255, 255));
        address_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        address_Label.setText("Address:");

        phone_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        phone_Label.setForeground(new java.awt.Color(255, 255, 255));
        phone_Label.setText("Phone:");

        clear_Button.setBackground(new java.awt.Color(51, 153, 255));
        clear_Button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        clear_Button.setForeground(new java.awt.Color(255, 255, 255));
        clear_Button.setText("CLEAR");
        clear_Button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        clear_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_ButtonActionPerformed(evt);
            }
        });

        heder_Label1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        heder_Label1.setForeground(new java.awt.Color(255, 255, 255));
        heder_Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heder_Label1.setText("Add a new customer");

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(phone_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firstname_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastname_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(address_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastname_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(address_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstname_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phone_TextField)))
                    .addComponent(heder_Label1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clear_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heder_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstname_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastname_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastname_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_Label))
                .addGap(35, 35, 35)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(clear_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        comandPanel.setBackground(new java.awt.Color(51, 153, 255));
        comandPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        saveButton.setBackground(new java.awt.Color(51, 153, 255));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/save.jpg"))); // NOI18N
        saveButton.setToolTipText("SAVE");
        saveButton.setBorder(null);
        saveButton.setBorderPainted(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        returnButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/return.png"))); // NOI18N
        returnButton2.setToolTipText("RETURN");
        returnButton2.setMaximumSize(new java.awt.Dimension(85, 85));
        returnButton2.setMinimumSize(new java.awt.Dimension(85, 85));
        returnButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout comandPanelLayout = new javax.swing.GroupLayout(comandPanel);
        comandPanel.setLayout(comandPanelLayout);
        comandPanelLayout.setHorizontalGroup(
            comandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comandPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        comandPanelLayout.setVerticalGroup(
            comandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comandPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(comandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        imgPanel.setBackground(new java.awt.Color(51, 153, 255));
        imgPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        img_for_new.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_for_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/pic2.png"))); // NOI18N

        javax.swing.GroupLayout imgPanelLayout = new javax.swing.GroupLayout(imgPanel);
        imgPanel.setLayout(imgPanelLayout);
        imgPanelLayout.setHorizontalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img_for_new, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        imgPanelLayout.setVerticalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imgPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(img_for_new, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout struct_PanelLayout = new javax.swing.GroupLayout(struct_Panel);
        struct_Panel.setLayout(struct_PanelLayout);
        struct_PanelLayout.setHorizontalGroup(
            struct_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(struct_PanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(struct_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comandPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        struct_PanelLayout.setVerticalGroup(
            struct_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(struct_PanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(struct_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(struct_PanelLayout.createSequentialGroup()
                        .addComponent(imgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comandPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(struct_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(struct_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clear_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_ButtonActionPerformed
        firstname_TextField.setText("");
        lastname_TextField.setText("");
        address_TextField.setText("");
        phone_TextField.setText("");
    }//GEN-LAST:event_clear_ButtonActionPerformed

    private void returnButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButton2ActionPerformed
        New_frame.super.setVisible(false);
        OptionFrame op = new OptionFrame();
        op.setLocationRelativeTo(null);
        op.setVisible(true);
    }//GEN-LAST:event_returnButton2ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String firstname = firstname_TextField.getText();
        String lastname = lastname_TextField.getText();
        String address = address_TextField.getText();
        String phone = phone_TextField.getText();

        if (firstname.equals("") || lastname.equals("") || address.equals("") || phone.equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter all information!", "Wrong enters!", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Customer.insertCustomer(firstname, lastname, address, phone);
                JOptionPane.showMessageDialog(null, "You have successfully saved a new customer", "New customer in database", JOptionPane.INFORMATION_MESSAGE);
                firstname_TextField.setText("");
                lastname_TextField.setText("");
                address_TextField.setText("");
                phone_TextField.setText("");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Connection error with the database!", "Bad connection!", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address_Label;
    private javax.swing.JTextField address_TextField;
    private javax.swing.JButton clear_Button;
    private javax.swing.JPanel comandPanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JLabel firstname_Label;
    private javax.swing.JTextField firstname_TextField;
    private javax.swing.JLabel heder_Label1;
    private javax.swing.JPanel imgPanel;
    private javax.swing.JLabel img_for_new;
    private javax.swing.JLabel lastname_Label;
    private javax.swing.JTextField lastname_TextField;
    private javax.swing.JLabel phone_Label;
    private javax.swing.JTextField phone_TextField;
    private javax.swing.JButton returnButton2;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel struct_Panel;
    // End of variables declaration//GEN-END:variables
}
