/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

/**
 *
 * @author Noko
 */
public class OptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form Workframe
     */
    public OptionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comand_Panel = new javax.swing.JPanel();
        new_Label = new javax.swing.JLabel();
        edit_Label = new javax.swing.JLabel();
        search_Label = new javax.swing.JLabel();
        title_new_Label = new javax.swing.JLabel();
        title_edit_Label = new javax.swing.JLabel();
        title_search_Label = new javax.swing.JLabel();
        logout_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comand_Panel.setBackground(new java.awt.Color(51, 153, 255));

        new_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/newuser.png"))); // NOI18N
        new_Label.setToolTipText("NEW CUSTOMER");
        new_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_LabelMouseClicked(evt);
            }
        });

        edit_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Edit1.png"))); // NOI18N
        edit_Label.setToolTipText("EDIT");
        edit_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_LabelMouseClicked(evt);
            }
        });

        search_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/search1.png"))); // NOI18N
        search_Label.setToolTipText("SEARCH");
        search_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_LabelMouseClicked(evt);
            }
        });

        title_new_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        title_new_Label.setForeground(new java.awt.Color(255, 255, 255));
        title_new_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_new_Label.setLabelFor(new_Label);
        title_new_Label.setText("New customer");

        title_edit_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        title_edit_Label.setForeground(new java.awt.Color(255, 255, 255));
        title_edit_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_edit_Label.setText("Edit customer");

        title_search_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        title_search_Label.setForeground(new java.awt.Color(255, 255, 255));
        title_search_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_search_Label.setText("Customer search");

        logout_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/exit.png"))); // NOI18N
        logout_Button.setToolTipText("LOGOUT");
        logout_Button.setBorder(null);
        logout_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout comand_PanelLayout = new javax.swing.GroupLayout(comand_Panel);
        comand_Panel.setLayout(comand_PanelLayout);
        comand_PanelLayout.setHorizontalGroup(
            comand_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comand_PanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(comand_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title_new_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(new_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(comand_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title_edit_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edit_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(comand_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comand_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(search_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addComponent(title_search_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(logout_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        comand_PanelLayout.setVerticalGroup(
            comand_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comand_PanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(comand_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_new_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(comand_PanelLayout.createSequentialGroup()
                        .addComponent(title_edit_Label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(title_search_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(comand_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_Label)
                    .addComponent(edit_Label)
                    .addComponent(search_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(logout_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comand_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comand_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_ButtonActionPerformed

//            OptionFrame wf = new OptionFrame();
        OptionFrame.super.setVisible(false);
        Login li = new Login();
        li.setLocationRelativeTo(null);
        li.setVisible(true);
    }//GEN-LAST:event_logout_ButtonActionPerformed

    private void new_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_LabelMouseClicked
        OptionFrame.super.setVisible(false);
        New_frame nf = new New_frame();
        nf.setLocationRelativeTo(null);
        nf.setVisible(true);
    }//GEN-LAST:event_new_LabelMouseClicked

    private void edit_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_LabelMouseClicked
         OptionFrame.super.setVisible(false);
        Edit_frame ef= new Edit_frame();
        ef.setLocationRelativeTo(null);
        ef.setVisible(true);
    }//GEN-LAST:event_edit_LabelMouseClicked

    private void search_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_LabelMouseClicked
        OptionFrame.super.setVisible(false);
        SearchJFrame sf = new SearchJFrame();
        sf.setLocationRelativeTo(null);
        sf.setVisible(true);
    }//GEN-LAST:event_search_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel comand_Panel;
    private javax.swing.JLabel edit_Label;
    private javax.swing.JButton logout_Button;
    private javax.swing.JLabel new_Label;
    private javax.swing.JLabel search_Label;
    private javax.swing.JLabel title_edit_Label;
    private javax.swing.JLabel title_new_Label;
    private javax.swing.JLabel title_search_Label;
    // End of variables declaration//GEN-END:variables
}
