/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import customer.Customer;
import javax.swing.JOptionPane;

/**
 *
 * @author Noko
 */
public class SearchJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SearchJFrame
     */
    public SearchJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        for_result_Panel = new javax.swing.JPanel();
        result_Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        heder_Panel = new javax.swing.JPanel();
        heder_Label = new javax.swing.JLabel();
        heder_img_Label = new javax.swing.JLabel();
        comand_Panel = new javax.swing.JPanel();
        select_Label = new javax.swing.JLabel();
        select_ComboBox = new javax.swing.JComboBox<>();
        key_Label = new javax.swing.JLabel();
        keyword_TextField = new javax.swing.JTextField();
        search_Button = new javax.swing.JButton();
        return_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        for_result_Panel.setBackground(new java.awt.Color(51, 153, 255));
        for_result_Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        result_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        result_Label.setForeground(new java.awt.Color(255, 255, 255));
        result_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        result_Label.setText("Search results");

        jScrollPane1.setBackground(new java.awt.Color(51, 153, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(51, 153, 255));
        jTextPane1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane1.setText("No search results!");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout for_result_PanelLayout = new javax.swing.GroupLayout(for_result_Panel);
        for_result_Panel.setLayout(for_result_PanelLayout);
        for_result_PanelLayout.setHorizontalGroup(
            for_result_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(for_result_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(for_result_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(result_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                .addContainerGap())
        );
        for_result_PanelLayout.setVerticalGroup(
            for_result_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(for_result_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        heder_Panel.setBackground(new java.awt.Color(51, 151, 255));
        heder_Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        heder_Label.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        heder_Label.setForeground(new java.awt.Color(255, 255, 255));
        heder_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heder_Label.setText("Search customers");

        heder_img_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/searchimage.png"))); // NOI18N

        javax.swing.GroupLayout heder_PanelLayout = new javax.swing.GroupLayout(heder_Panel);
        heder_Panel.setLayout(heder_PanelLayout);
        heder_PanelLayout.setHorizontalGroup(
            heder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heder_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heder_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(heder_img_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        heder_PanelLayout.setVerticalGroup(
            heder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, heder_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(heder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(heder_img_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(heder_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        comand_Panel.setBackground(new java.awt.Color(51, 153, 255));
        comand_Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        select_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        select_Label.setForeground(new java.awt.Color(255, 255, 255));
        select_Label.setText("Select search by:");

        select_ComboBox.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        select_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First name", "Last name", "Address", "Phone number" }));

        key_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        key_Label.setForeground(new java.awt.Color(255, 255, 255));
        key_Label.setText("Enter a search keyword:");

        keyword_TextField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        search_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/serpic.png"))); // NOI18N
        search_Button.setToolTipText("SEARCH");
        search_Button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        search_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_ButtonActionPerformed(evt);
            }
        });

        return_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/return.png"))); // NOI18N
        return_Button.setToolTipText("RETURN");
        return_Button.setBorder(null);
        return_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout comand_PanelLayout = new javax.swing.GroupLayout(comand_Panel);
        comand_Panel.setLayout(comand_PanelLayout);
        comand_PanelLayout.setHorizontalGroup(
            comand_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comand_PanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(comand_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(select_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(comand_PanelLayout.createSequentialGroup()
                        .addComponent(keyword_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(comand_PanelLayout.createSequentialGroup()
                        .addComponent(search_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(return_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(comand_PanelLayout.createSequentialGroup()
                        .addGroup(comand_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(key_Label)
                            .addComponent(select_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        comand_PanelLayout.setVerticalGroup(
            comand_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comand_PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(select_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(select_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(key_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(keyword_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(comand_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(return_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(heder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comand_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(for_result_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(for_result_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(heder_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comand_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void return_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_ButtonActionPerformed
        SearchJFrame.super.setVisible(false);
        OptionFrame op = new OptionFrame();
        op.setLocationRelativeTo(null);
        op.setVisible(true);
    }//GEN-LAST:event_return_ButtonActionPerformed

    private void search_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_ButtonActionPerformed

        String search_by = null;
        String keyword = keyword_TextField.getText();
        switch (select_ComboBox.getSelectedItem().toString()) {

            case "First name": {
                search_by = "first_name";
            }
            break;

            case "Last name": {
                search_by = "last_name";
            }
            break;

            case "Address": {
                search_by = "address";
            }
            break;

            case "Phone number": {
                search_by = "phone";
            }
            break;
        }
        try {
            if (search_by == null || keyword.equals("")) {
                JOptionPane.showMessageDialog(null, "You must enter keyword!", "Wrong enters", JOptionPane.ERROR_MESSAGE);
            } else {
                jTextPane1.setText(Customer.customer_Search(search_by, keyword));
                keyword_TextField.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection error", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_search_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel comand_Panel;
    private javax.swing.JPanel for_result_Panel;
    private javax.swing.JLabel heder_Label;
    private javax.swing.JPanel heder_Panel;
    private javax.swing.JLabel heder_img_Label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel key_Label;
    private javax.swing.JTextField keyword_TextField;
    private javax.swing.JLabel result_Label;
    private javax.swing.JButton return_Button;
    private javax.swing.JButton search_Button;
    private javax.swing.JComboBox<String> select_ComboBox;
    private javax.swing.JLabel select_Label;
    // End of variables declaration//GEN-END:variables
}
